services:
  logging-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-logging:/var/opt/mssql
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD-SHELL", "pgrep sqlservr" ]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 5s

  loggingapi:
    build:
      context: .
      dockerfile: LoggingApi/Dockerfile
    deploy:
      replicas: 2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      migration_service:
        condition: service_completed_successfully

  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - loggingapi
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  
  # Esben and Asbjørn fandt ud af dette
  migration_service:
    build:
      context: .
      dockerfile: LoggingApi/Migrations.Dockerfile
    depends_on:
      logging-db:
        condition: service_healthy

volumes:
  mssql-logging: