services:
  logging-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-logging:/var/opt/mssql
    ports:
      - "1433:1433"

  loggingapi:
    build:
      context: .
      dockerfile: LoggingApi/Dockerfile
    deploy:
      replicas: 1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      logging-db:
        condition: service_started

  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - loggingapi
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  mssql-logging: