// <auto-generated />
using System;
using LoggingApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoggingApi.Migrations
{
    [DbContext(typeof(LADbContext))]
    [Migration("20240930104331_updateLoggingKey")]
    partial class updateLoggingKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Logging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LoggingString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentSpanId")
                        .HasColumnType("int");

                    b.Property<int>("SpanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("TraceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("logging");
                });
#pragma warning restore 612, 618
        }
    }
}
