// <auto-generated />
using System;
using LoggingApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoggingApi.Migrations
{
    [DbContext(typeof(LADbContext))]
    partial class LADbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Logging", b =>
                {
                    b.Property<int>("SpanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpanId"));

                    b.Property<string>("LoggingString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentSpanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("TraceId")
                        .HasColumnType("int");

                    b.HasKey("SpanId");

                    b.HasIndex("ParentSpanId");

                    b.ToTable("logging");
                });

            modelBuilder.Entity("Model.Logging", b =>
                {
                    b.HasOne("Model.Logging", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentSpanId");

                    b.Navigation("Parent");
                });
#pragma warning restore 612, 618
        }
    }
}
